# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_cards.ipynb"}

modules = ["card.py"]

doc_url = "https://alexanderhogheim.github.io/nbdev-tutorial/"

git_url = "https://github.com/alexanderhogheim/nbdev-tutorial/tree/{branch}/"

def custom_doc_links(name): return None
